// Constants for ResumeIQ ATS scoring engine

export const SKILLS_KEYWORDS = [
    "JavaScript",
    "React",
    "Node",
    "Python",
    "SQL",
    "MongoDB",
    "Machine Learning",
    "HTML",
    "CSS",
    "Docker",
    "AWS",
    "Express",
    "Next.js",
    "TypeScript",
    "REST API",
    "Git",
    "Linux",
    "PostgreSQL",
    "GraphQL",
    "Redis",
    "Kubernetes",
    "CI/CD",
    "Agile",
    "TensorFlow",
    "PyTorch",
    "Angular",
    "Vue",
    "Java",
    "C++",
    "Go",
    "Rust",
    "Swift",
    "Kotlin",
    "Flutter",
    "React Native",
    "Firebase",
    "Azure",
    "GCP",
    "Webpack",
    "Vite",
];

export const EDUCATION_KEYWORDS = [
    "B.Tech",
    "Bachelor",
    "CGPA",
    "University",
    "Degree",
    "Master",
    "M.Tech",
    "B.E",
    "B.Sc",
    "M.Sc",
    "MBA",
    "Ph.D",
    "College",
    "Institute",
    "GPA",
    "Engineering",
    "Science",
    "Arts",
    "Commerce",
];

export const PROJECT_VERBS = [
    "Developed",
    "Built",
    "Designed",
    "Implemented",
    "Optimized",
    "Engineered",
    "Created",
    "Deployed",
    "Architected",
    "Integrated",
    "Automated",
    "Led",
    "Managed",
    "Delivered",
    "Reduced",
    "Improved",
    "Increased",
    "Launched",
    "Migrated",
    "Refactored",
];

export const MEASURABLE_WORDS = [
    "%",
    "percent",
    "increased",
    "reduced",
    "improved",
    "decreased",
    "boosted",
    "achieved",
    "grew",
    "saved",
    "optimized",
    "accelerated",
    "doubled",
    "tripled",
    "halved",
];

export const ATS_IMPORTANT_KEYWORDS = [
    "experience",
    "skills",
    "projects",
    "education",
    "summary",
    "objective",
    "achievements",
    "certifications",
    "languages",
    "references",
];

export const MAX_FILE_SIZE_MB = 10;
export const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;

export const SCORE_WEIGHTS: Record<string, number> = {
    contactInfo: 10,
    skills: 20,
    projects: 20,
    education: 15,
    keywordMatch: 20,
    structureFormatting: 15,
};

export const SECTION_HEADERS = [
    "EXPERIENCE",
    "EDUCATION",
    "SKILLS",
    "PROJECTS",
    "SUMMARY",
    "OBJECTIVE",
    "CERTIFICATIONS",
    "ACHIEVEMENTS",
    "AWARDS",
    "PUBLICATIONS",
    "VOLUNTEER",
    "LANGUAGES",
    "INTERESTS",
    "REFERENCES",
    "CONTACT",
    "PROFILE",
];
