import { NextResponse } from "next/server";

export const runtime = "nodejs";

export async function GET() {
    try {
        const templates = [
            // MODERN - 10 templates
            {
                id: "modern-clean",
                name: "Modern Clean",
                category: "Modern",
                description: "Clean and professional with blue accents",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "modern-minimal",
                name: "Modern Minimal",
                category: "Modern",
                description: "Minimal design with sans-serif typography",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "modern-bold",
                name: "Modern Bold",
                category: "Modern",
                description: "Bold header with dark sidebar",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "modern-sidebar",
                name: "Modern Sidebar",
                category: "Modern",
                description: "Two-column layout with sidebar",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "modern-hybrid",
                name: "Modern Hybrid",
                category: "Modern",
                description: "Grid-based modern layout",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "modern-tech-1",
                name: "Tech Stack",
                category: "Modern",
                description: "Perfect for tech professionals",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "modern-tech-2",
                name: "Developer",
                category: "Modern",
                description: "Design-focused tech layout",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "modern-tech-3",
                name: "Code",
                category: "Modern",
                description: "Minimalist code-focused template",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "modern-innovative-1",
                name: "Innovative Flow",
                category: "Modern",
                description: "Modern flow with accent colors",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "modern-innovative-2",
                name: "Innovative Plus",
                category: "Modern",
                description: "Enhanced innovative layout",
                isATS: true,
                isResponsive: true,
            },

            // CORPORATE - 10 templates
            {
                id: "corporate-classic",
                name: "Corporate Classic",
                category: "Corporate",
                description: "Traditional serif-based corporate style",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "corporate-professional",
                name: "Corporate Professional",
                category: "Corporate",
                description: "Standard professional corporate format",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "corporate-executive",
                name: "Corporate Executive",
                category: "Corporate",
                description: "Executive-level professional design",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "corporate-formal-1",
                name: "Formal Business",
                category: "Corporate",
                description: "Formal business presentation",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "corporate-formal-2",
                name: "Formal Elite",
                category: "Corporate",
                description: "Elite formal corporate style",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "corporate-structured-1",
                name: "Structured Office",
                category: "Corporate",
                description: "Highly structured corporate layout",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "corporate-structured-2",
                name: "Structured Pro",
                category: "Corporate",
                description: "Professional structured format",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "corporate-modern-1",
                name: "Modern Corporate",
                category: "Corporate",
                description: "Contemporary corporate design",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "corporate-modern-2",
                name: "Corporate Plus",
                category: "Corporate",
                description: "Enhanced modern corporate",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "corporate-premium",
                name: "Corporate Premium",
                category: "Corporate",
                description: "Premium corporate presentation",
                isATS: true,
                isResponsive: true,
            },

            // EXECUTIVE - 10 templates
            {
                id: "executive-standard",
                name: "Executive Standard",
                category: "Executive",
                description: "Standard executive format",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "executive-premium",
                name: "Executive Premium",
                category: "Executive",
                description: "Premium executive design",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "executive-elite",
                name: "Executive Elite",
                category: "Executive",
                description: "Elite executive-level template",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "executive-ceo",
                name: "CEO Resume",
                category: "Executive",
                description: "Executive-level CEO template",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "executive-leadership",
                name: "Leadership",
                category: "Executive",
                description: "Leadership-focused template",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "executive-strategic",
                name: "Strategic",
                category: "Executive",
                description: "Strategic executive layout",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "executive-visionary",
                name: "Visionary",
                category: "Executive",
                description: "Visionary executive design",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "executive-director",
                name: "Director",
                category: "Executive",
                description: "Director-level template",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "executive-manager",
                name: "Manager Pro",
                category: "Executive",
                description: "Manager-level professional",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "executive-senior",
                name: "Senior Executive",
                category: "Executive",
                description: "Senior executive template",
                isATS: true,
                isResponsive: true,
            },

            // MINIMAL - 10 templates
            {
                id: "minimal-ats",
                name: "Minimal ATS",
                category: "Minimal",
                description: "ATS-optimized minimal format",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "minimal-elegant",
                name: "Minimal Elegant",
                category: "Minimal",
                description: "Elegant minimal serif design",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "minimal-clean-1",
                name: "Clean Minimal",
                category: "Minimal",
                description: "Ultra-clean minimal layout",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "minimal-clean-2",
                name: "Clean Pro",
                category: "Minimal",
                description: "Professional clean template",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "minimal-simple-1",
                name: "Simple",
                category: "Minimal",
                description: "Simple and straightforward",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "minimal-simple-2",
                name: "Simple Plus",
                category: "Minimal",
                description: "Enhanced simple layout",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "minimal-monochrome-1",
                name: "Monochrome",
                category: "Minimal",
                description: "Monochrome minimal style",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "minimal-monochrome-2",
                name: "Monochrome Plus",
                category: "Minimal",
                description: "Enhanced monochrome design",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "minimal-stark-1",
                name: "Stark",
                category: "Minimal",
                description: "Stark minimal design",
                isATS: true,
                isResponsive: true,
            },
            {
                id: "minimal-stark-2",
                name: "Stark Pro",
                category: "Minimal",
                description: "Professional stark layout",
                isATS: true,
                isResponsive: true,
            },

            // CREATIVE - 10 templates
            {
                id: "creative-colorful",
                name: "Creative Colorful",
                category: "Creative",
                description: "Vibrant colorful design",
                isATS: false,
                isResponsive: true,
            },
            {
                id: "creative-gradient",
                name: "Creative Gradient",
                category: "Creative",
                description: "Gradient-based creative layout",
                isATS: false,
                isResponsive: true,
            },
            {
                id: "creative-artistic-1",
                name: "Artistic",
                category: "Creative",
                description: "Artistic creative template",
                isATS: false,
                isResponsive: true,
            },
            {
                id: "creative-artistic-2",
                name: "Artistic Plus",
                category: "Creative",
                description: "Enhanced artistic design",
                isATS: false,
                isResponsive: true,
            },
            {
                id: "creative-modern-1",
                name: "Modern Creative",
                category: "Creative",
                description: "Modern creative style",
                isATS: false,
                isResponsive: true,
            },
            {
                id: "creative-modern-2",
                name: "Modern Creative Pro",
                category: "Creative",
                description: "Professional modern creative",
                isATS: false,
                isResponsive: true,
            },
            {
                id: "creative-bold-1",
                name: "Bold Creative",
                category: "Creative",
                description: "Bold creative design",
                isATS: false,
                isResponsive: true,
            },
            {
                id: "creative-bold-2",
                name: "Bold Pro",
                category: "Creative",
                description: "Professional bold template",
                isATS: false,
                isResponsive: true,
            },
            {
                id: "creative-vibrant-1",
                name: "Vibrant",
                category: "Creative",
                description: "Vibrant creative layout",
                isATS: false,
                isResponsive: true,
            },
            {
                id: "creative-vibrant-2",
                name: "Vibrant Plus",
                category: "Creative",
                description: "Enhanced vibrant design",
                isATS: false,
                isResponsive: true,
            },
            {"id":"technical-engineer","name":"Engineer Pro","category":"Technical","description":"Technical engineering layout","isATS":true,"isResponsive":true},
            {"id":"technical-devops","name":"DevOps","category":"Technical","description":"Infrastructure and DevOps focus","isATS":true,"isResponsive":true},
            {"id":"technical-data","name":"Data Scientist","category":"Technical","description":"Data and analytics layout","isATS":true,"isResponsive":true},
            {"id":"technical-security","name":"Security Analyst","category":"Technical","description":"Cybersecurity focused","isATS":true,"isResponsive":true},
            {"id":"technical-cloud","name":"Cloud Architect","category":"Technical","description":"Cloud and architecture design","isATS":true,"isResponsive":true},
            {"id":"technical-frontend","name":"Frontend Developer","category":"Technical","description":"UI/UX focused tech layout","isATS":true,"isResponsive":true},
            {"id":"technical-backend","name":"Backend Developer","category":"Technical","description":"Server-side and API focus","isATS":true,"isResponsive":true},
            {"id":"technical-fullstack","name":"Full Stack","category":"Technical","description":"Comprehensive tech layout","isATS":true,"isResponsive":true},
            {"id":"technical-mobile","name":"Mobile Developer","category":"Technical","description":"iOS and Android focus","isATS":true,"isResponsive":true},
            {"id":"technical-qa","name":"QA Engineer","category":"Technical","description":"Quality assurance template","isATS":true,"isResponsive":true},
            {"id":"medical-doctor","name":"Physician","category":"Medical","description":"Clinical and medical layout","isATS":true,"isResponsive":true},
            {"id":"medical-nurse","name":"Nursing Professional","category":"Medical","description":"Nursing and patient care focus","isATS":true,"isResponsive":true},
            {"id":"medical-research","name":"Clinical Research","category":"Medical","description":"Medical research focused","isATS":true,"isResponsive":true},
            {"id":"medical-surgeon","name":"Surgeon","category":"Medical","description":"Surgical and specialized care","isATS":true,"isResponsive":true},
            {"id":"medical-admin","name":"Healthcare Admin","category":"Medical","description":"Healthcare management layout","isATS":true,"isResponsive":true},
            {"id":"medical-dental","name":"Dental Professional","category":"Medical","description":"Dentistry and oral care","isATS":true,"isResponsive":true},
            {"id":"medical-pharmacy","name":"Pharmacist","category":"Medical","description":"Pharmacy and medication focus","isATS":true,"isResponsive":true},
            {"id":"medical-therapy","name":"Physical Therapist","category":"Medical","description":"Rehabilitation layout","isATS":true,"isResponsive":true},
            {"id":"medical-tech","name":"Medical Technician","category":"Medical","description":"Lab and technology focus","isATS":true,"isResponsive":true},
            {"id":"medical-specialist","name":"Medical Specialist","category":"Medical","description":"Specialized clinical layout","isATS":true,"isResponsive":true},
            {"id":"academic-professor","name":"Professor","category":"Academic","description":"Higher education focus","isATS":true,"isResponsive":true},
            {"id":"academic-research","name":"Postdoc Researcher","category":"Academic","description":"Research and publications layout","isATS":true,"isResponsive":true},
            {"id":"academic-teacher","name":"Educator","category":"Academic","description":"K-12 teaching focused","isATS":true,"isResponsive":true},
            {"id":"academic-admin","name":"Academic Admin","category":"Academic","description":"Education management layout","isATS":true,"isResponsive":true},
            {"id":"academic-student","name":"Graduate Student","category":"Academic","description":"Student and fellowship layout","isATS":true,"isResponsive":true},
            {"id":"academic-counselor","name":"School Counselor","category":"Academic","description":"Student services focus","isATS":true,"isResponsive":true},
            {"id":"academic-librarian","name":"Librarian","category":"Academic","description":"Library and information science","isATS":true,"isResponsive":true},
            {"id":"academic-adjunct","name":"Adjunct Faculty","category":"Academic","description":"Part-time teaching layout","isATS":true,"isResponsive":true},
            {"id":"academic-dean","name":"Dean of Students","category":"Academic","description":"Executive academic layout","isATS":true,"isResponsive":true},
            {"id":"academic-fellow","name":"Research Fellow","category":"Academic","description":"Fellowship and grant focus","isATS":true,"isResponsive":true},
            {"id":"sales-executive","name":"Sales Executive","category":"Sales","description":"High-level sales layout","isATS":true,"isResponsive":true},
            {"id":"sales-manager","name":"Sales Manager","category":"Sales","description":"Team management focus","isATS":true,"isResponsive":true},
            {"id":"sales-rep","name":"Sales Representative","category":"Sales","description":"Direct sales focused","isATS":true,"isResponsive":true},
            {"id":"sales-b2b","name":"B2B Sales","category":"Sales","description":"Business to business layout","isATS":true,"isResponsive":true},
            {"id":"sales-retail","name":"Retail Manager","category":"Sales","description":"Retail and store management","isATS":true,"isResponsive":true},
            {"id":"sales-account","name":"Account Executive","category":"Sales","description":"Client relationship focus","isATS":true,"isResponsive":true},
            {"id":"sales-dev","name":"Business Development","category":"Sales","description":"Growth and strategy layout","isATS":true,"isResponsive":true},
            {"id":"sales-inside","name":"Inside Sales","category":"Sales","description":"Inbound sales focus","isATS":true,"isResponsive":true},
            {"id":"sales-regional","name":"Regional Director","category":"Sales","description":"Territory management layout","isATS":true,"isResponsive":true},
            {"id":"sales-vp","name":"VP of Sales","category":"Sales","description":"Executive sales layout","isATS":true,"isResponsive":true},
            {"id":"legal-attorney","name":"Attorney","category":"Legal","description":"Classic law practice layout","isATS":true,"isResponsive":true},
            {"id":"legal-corporate","name":"Corporate Counsel","category":"Legal","description":"In-house legal focus","isATS":true,"isResponsive":true},
            {"id":"legal-paralegal","name":"Paralegal","category":"Legal","description":"Legal support focused","isATS":true,"isResponsive":true},
            {"id":"legal-partner","name":"Law Partner","category":"Legal","description":"Executive law firm layout","isATS":true,"isResponsive":true},
            {"id":"legal-clerk","name":"Law Clerk","category":"Legal","description":"Clerkship and judicial focus","isATS":true,"isResponsive":true},
            {"id":"legal-compliance","name":"Compliance Officer","category":"Legal","description":"Regulatory compliance layout","isATS":true,"isResponsive":true},
            {"id":"legal-litigation","name":"Litigator","category":"Legal","description":"Trial and litigation focus","isATS":true,"isResponsive":true},
            {"id":"legal-associate","name":"Associate Attorney","category":"Legal","description":"Law firm associate layout","isATS":true,"isResponsive":true},
            {"id":"legal-assistant","name":"Legal Assistant","category":"Legal","description":"Administrative legal focus","isATS":true,"isResponsive":true},
            {"id":"legal-advisor","name":"Legal Advisor","category":"Legal","description":"Consulting legal layout","isATS":true,"isResponsive":true},
        ];

        const atsReadyTemplates = templates.map((template) => ({
            ...template,
            isATS: true,
            atsScore: 100,
        }));

        return NextResponse.json({ templates: atsReadyTemplates }, { status: 200 });
    } catch (error: unknown) {
        console.error("[/api/templates] Error:", error);
        return NextResponse.json({ error: "Failed to fetch templates" }, { status: 500 });
    }
}

export async function POST() {
    return GET();
}
